name: Run Azure Login with OpenID Connect

on:
  workflow_dispatch:
    branches: [main]
    inputs:
      environment:
        description: "Environment Name"
        type: environment
        default: "production"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: "Get Environment Name"
        run: |
          echo "Environment Name: ${{ github.event.inputs.environment }}"
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Run Azure CLI commands"
        run: |
          az keyvault secret list --vault-name ${{secrets.KEY_VAULT_NAME }} --query "[].name" -o tsv
